### ISSUE TITLE
Cmd not Ctrl for moving frame selection on Apple Mac

### ISSUE THREAD

**Issue by nbrockington** [elan-language/Documentation#184]
I just noticed that on an Apple Mac keyboard (using Chrome browser), it is Cmd-↑ and Cmd-↓ for moving the frame selection up and down within peer level, not Ctrl-↑ etc. as noted on the Documentation (which is presumably for other machines).

**Comment by richardpawson** [comment]
Thanks, Nela. I have updated the Reference Manual to reflect this, but also moved the manual back into the main (LanguageAndIDE) repository, and will be closing this one, as issues less likely to get lost that way.
